version: '3'
services:
  api:
    build: .
    ports:
      - "3000:80"
    environment:
      - port=80
      - gzipOff=true
      #- NODE_ENV=production
    volumes:
      - .:/app
    working_dir: /app
    command: 'sh -c "npm i && npm run dev"'
